### PR TITLE
Release v0.0.1

### PR DESCRIPTION
**Pull request by erikscheurer**
This PR corrects the `Project.toml` and bots, so we can test a first release for the bindings to the Julia general repository

### CODE REVIEW

**Comment by erikscheurer** [comment]
It seems like the [Julia Version number literals](https://docs.julialang.org/en/v1/manual/strings/#man-version-number-literals) are only able to contain 3 numbers.

**Comment by IshaanDesai** [comment]
Lets try `v2.4.0_0` and see if Julia likes it

**Comment by IshaanDesai** [comment]
> Should we do a `2.4.0-rc1` release or name it `2.4.0-0`?

Lets do a `v2.4.0-0-rc1` as the first release candidate. We can do it using the following steps:

1. Change the version in Project.toml to `v2.4.0-0-rc1`
2. Create a release in the [releases](https://github.com/precice/julia-bindings/releases) which points to main branch. The release tag will always have the version as its name, so `v2.4.0-0-rc1` in this case. At this point we just create the release and not release it, so we create it and save it.
3. Change the name of this PR to **Release v2.4.0-0-rc1**
4. When all checks pass (they already have), we merge this to main
5. Once all the checks pass on main, we release!

One more thing to keep in mind is that, once we release the first candidate from main, we will create a branch called `develop` from main. This branch will be used to all the newer developments which are not part of the latest release. So the `main` branch will always correspond to the latest released state and the `develop` branch will correspond to the latest state of the bindings.

**Comment by IshaanDesai** [comment]
@JuliaRegistrator register branch=testRelease

**Review by IshaanDesai — APPROVED** [review]
Ready for trial release :+1:

**Pull request merged**
